domain: production.kublab.org
image:
  registry: ghcr.io/giannisstathoudakis
  pullPolicy: Always

security:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000
  readOnlyRootFilesystem: false

mysql:
  host: mysql.mysql.svc.cluster.local
  port: 3306
  databaseName: ecommerce

redpanda:
  bootstrapServers: "redpanda.redpanda.svc.cluster.local:9093"

microservices:
  orders:
    name: ms-orders
    port: 9091
    tag: 88fc332d39aae80bdc7d766bd36ef4cf0c39bb8e
    path: /orders
  payment:
    name: ms-payment
    port: 8080
    tag: 88fc332d39aae80bdc7d766bd36ef4cf0c39bb8e
    path: /payment
  stock:
    name: ms-stock
    port: 8080
    tag: 88fc332d39aae80bdc7d766bd36ef4cf0c39bb8e
    path: /stock
