---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ecommerce-routes
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: lab-gateway
    namespace: envoy-gateway-system
    sectionName: https
  hostnames: 
  - {{ .Values.domain | quote }}
  rules:
  {{- range .Values.microservices }}
  {{- if .path }}
  - matches:
    - path:
        type: PathPrefix
        value: {{ .path }}
    backendRefs:
    - name: {{ .name }}
      port: {{ .port }}
  {{- end }}
  {{- end }}