{{- range .Values.microservices }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      serviceAccountName: {{ .name }}-sa
      securityContext:
        runAsNonRoot: {{ $.Values.security.runAsNonRoot }}
        runAsUser: {{ $.Values.security.runAsUser }}
        runAsGroup: {{ $.Values.security.runAsGroup }}
      containers:
        - name: {{ .name }}
          image: "{{ $.Values.image.registry }}/{{ .name }}:{{ .tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .port }}
          env:
            # Redpanda connection
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: {{ $.Values.redpanda.bootstrapServers | quote }}
            
            # MySQL connection
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://{{ $.Values.mysql.host }}:{{ $.Values.mysql.port }}/{{ $.Values.mysql.databaseName }}?useSSL=false&allowPublicKeyRetrieval=true"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}-db-secret
                  key: MYSQL_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}-db-secret
                  key: MYSQL_PASSWORD
            # Dynamic JVM Memory Management (80% Heap, 20% Off-Heap Buffer)
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms{{ div (mul .resources.requests.memoryMb 80) 100 }}m -Xmx{{ div (mul .resources.limits.memoryMb 80) 100 }}m"

            # Alloy settigns
            - name: OTEL_SERVICE_NAME
              value: "{{ .name }}"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://alloy.argocd.svc.cluster.local:4317"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            - name: GRAFANA_OTEL_PROFILER_ENABLED
              value: "true"
            - name: GRAFANA_OTEL_PROFILER_ENDPOINT
              value: "http://pyroscope-distributor.pyroscope.svc.cluster.local:4040"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name={{ .name }},k8s.namespace.name={{ $.Release.Namespace }},k8s.cluster.name=my-prod-cluster"

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3

          resources:
            requests:
              cpu: "{{ .resources.requests.cpuMilli }}m"
              memory: "{{ .resources.requests.memoryMb }}Mi"
            limits:
              cpu: "{{ .resources.limits.cpuMilli }}m"
              memory: "{{ .resources.limits.memoryMb }}Mi"
{{- end }}