{{- range .Values.microservices }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}-db-credentials
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-db-backend
    kind: ClusterSecretStore
  target:
    name: {{ .name }}-db-secret
    creationPolicy: Owner
    template:
      data:
        MYSQL_USERNAME: '{{ "{{" }} .username {{ "}}" }}'
        MYSQL_PASSWORD: '{{ "{{" }} .password {{ "}}" }}'
  dataFrom:
  - extract:
      key: database/creds/{{ .name }}-role
{{- end }}